### ISSUE TITLE
Cannot reconnect errors

### ISSUE THREAD

**Issue by cyberjunky** [hassio-addons/addon-vscode#96] opened 2020-04-16 12:22 UTC
# Problem/Motivation
Using 2.2.0 with Hassio 0.108.5 and the editor keeps bailing out with this error:

![Screenshot from 2020-04-16 14-09-36](https://user-images.githubusercontent.com/5447161/79455504-4207b700-7fed-11ea-982e-ea81ff172a82.png)

I find this in the logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Visual Studio Code
 Fully featured VSCode experience, to edit your HA config in the browser, including auto-completion!
-----------------------------------------------------------
 Add-on version: 2.2.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 0.108.5
 Home Assistant Supervisor: 217
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] code-server.sh: executing... 
[cont-init.d] code-server.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] user.sh: executing... 
[cont-init.d] user.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:39:24] INFO: Starting the code server...
info  code-server 3.1.1 28e91ba70cd70fa9adf3f2e3e3b87631b5667ecf
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS
info  Automatic updates are disabled
info  SSH server disabled
(node:435) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
(node:435) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
```
> (Why the issue was filed)

## Expected behavior

Without the errors.
> (What you expected to happen)

## Actual behavior

Unable to edit properly.
Files do not always open, errors.

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by Sterion** [comment] 2020-04-20 15:06
Had the exact same problem, downgrading to 2.1.0 solved it for me (But brought back the upgrade notice each and every time addon was activated.. but hey at least it works)

**Comment by jsb5151** [comment] 2020-04-20 22:21
Same issue here.   "Cannot reconnect. Please reload the window."

If you have a quick way to revert to 2.1.0 that would be perfect...

**Comment by sinclairpaul** [comment] 2020-04-20 22:48
Not sure how anyone can duplicate this, maybe you could all post installed extensions, config and hardware details to try and find a common issue?

**Comment by cyberjunky** [comment] 2020-04-21 07:27
The problem went away after some time, no idea why.
I run on a UDOO x86 ubuntu OS, latest hass.io home.assistant

**Comment by StealthChesnut** [comment] 2020-04-21 10:35
I have had the same issue since Friday. I have also just had it apparently disappear. I had the syntax checker highlight problems and then clear them off again just at the same point in time that I would expect to see the error pop up (a few seconds after opening the VScode tab), but no errors this morning.

My setup is:
 Add-on version: 2.2.0
 You are running the latest version of this add-on.
 System: Ubuntu 16.04.6 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 0.108.5
 Home Assistant Supervisor: 217

My system is a VM on proxmox.

**Comment by nickm324** [comment] 2020-04-21 22:13
New install today, Same issue constant reconnect notices, any fix for this?

**Comment by sinclairpaul** [comment] 2020-04-21 22:35
@nickm324 Fix for what you haven't provided many details..., as suggested previously please post your hardware and config.

In all honesty from what I see in this issue it is a resource problem, especially how it suddenly stops occuring.

**Comment by nickm324** [comment] 2020-04-22 01:08
My setup is:
Add-on version: 2.2.0
You are running the latest version of this add-on.
System: Ubuntu Server 18.04.4 LTS
Home Assistant Core: 0.108.6
Home Assistant Supervisor: 217

**Comment by fboterblom** [comment] 2020-04-22 09:48
I have the same issue, because I have made a vm snapshot I could determine that the problem is starting after the upgrade of the Visual studio add-on.

**Comment by nickm324** [comment] 2020-04-24 16:12
> @nickm324 Fix for what you haven't provided many details..., as suggested previously please post your hardware and config.
> 
> In all honesty from what I see in this issue it is a resource problem, especially how it suddenly stops occuring.

A fix for it constantly wanting to reconnect and completely reloading the page over and over. This is a brand new install and it did not just GO Away for me. Going to try uninstalling and reinstalling.

**Comment by frenck** [comment] 2020-04-24 16:48
I really want to help out on this, but I haven't been able to reproduce any of these symptoms on any of my systems... 😢

**Comment by nickm324** [comment] 2020-04-24 17:20
Maybe this is some how related to whats causing the issue. I uninstalled it. Then re-installed. Everything seemed to be working fine for about 10 minutes. Then since it only shows the configuration folder,   I went to the file menu and told it to open a new folder and selected the SSL folder one level up. As soon as I did that I started getting the RECONNECT issue again and even going back to the configuration folder did not fix the issue. Not sure if that provides any useful info but it may be related. I did the same thing on the first install also and had the issue.

**Comment by Frits1980** [comment] 2020-04-26 15:52
I have the issue two.
Doesn't go away yet. Even with a long lived access token.
intel-nuc
Ubuntu 18.04
vscode 2.2.0
supervisor 219
HA 0.108.9
![2622898e200cdcdce53c4cc82b0e37e3015064b9](https://user-images.githubusercontent.com/6774843/80312642-785fe600-87e6-11ea-8263-742c1508b51e.png)


To solve it I have removed the addon completly (removed the image from Docker, don't believe this is important though) and reinstalled the addon.

**Comment by faelterman** [comment] 2020-04-28 13:08
I have this too since a couple of days. Home assistant running in VM on Unraid. 
vscode 2.2.0
supervisor 219
HassOS 3.13

**Comment by jrnhrmn** [comment] 2020-04-29 20:51
Same issue here and no extra info. Sorry @frenck

**Comment by Adorem** [comment] 2020-05-01 18:10
I also get this if I open VS Code from left menu and then go with this URL :
![image](https://user-images.githubusercontent.com/38832853/80829364-4932e580-8be7-11ea-9696-0e87871d485a.png)
Works if I open from Supervisor > Visual Studio Code > open web ui corresponding to this URL :
![image](https://user-images.githubusercontent.com/38832853/80829605-c2323d00-8be7-11ea-927a-39587fbc5936.png)

Hope it helps.

**Comment by Frits1980** [comment] 2020-05-04 08:28
@adorem, thanks for sharing, though both have the same issue with me.

**Comment by Frits1980** [comment] 2020-05-04 08:32
@frenck , since you obviously can't debug a problem which you don't have. Is it an idea to setup a teamviewer (or alike) meeting to see if you can figure this out? I already put the add-on debug level on trace, but no errors in the log when it happens. actually no errors at all. So i'm at a loss.

**Comment by Adorem** [comment] 2020-05-04 12:07
> @Adorem, thanks for sharing, though both have the same issue with me.

Yes I notice after my message I can get the error with the two URL. But then I also not get the error all the time.

But I'm looking for a solution too.

**Comment by Frits1980** [comment] 2020-05-04 16:20
@adorem, I've been trying something. Could you help me and try it too?
When I load the vscode screen I see the breadcrumb above the last opened file. It takes a couple of seconds to totally load (i mean beyond the file path, object path, json path etc.). When I wait unitl it is fully loaded (about 4 seconds) before doing anything in vscode I hardly ever get the connection error. Can you verify that? Thanks

**Comment by Frits1980** [comment] 2020-05-05 12:16
Testing some more, i can for 80% say it's related to having more than one (chrome) window/tab with HA open. It doesn't matter if that window/tab has vscode in it or a dashboard or something else, as long as HA is running in it, vscode is getting these connection errors more frequently.

**Comment by faelterman** [comment] 2020-05-05 12:20
Ok, I'll try that tonight. See if I can confirm on this...
Would having the android app running have influence on this? Anyways I'll try with everything off first.

**Comment by Frits1980** [comment] 2020-05-05 12:27
I doubt it, because it's always running on the background with me and I have moments when I don't get the errors for a long time.

Also if I close all other browser tabs I have the hard refresh (ctrl+r ) the first before i get it working without errors.

**Comment by josco95** [comment] 2020-05-10 19:11
Same issue using Firefox, fresh HassOS 3.13 install today (no customization or configuration, only installing add-ons [config checker, node-red, and this one]), no other open tabs, works on refresh but seems to randomly decide when to stop working (I can click on two files first time, only one the second time, etc..etc..). The following is observed in the app log:
```
[14:58:05] INFO: Starting the code server...
info  code-server 3.1.1 28e91ba70cd70fa9adf3f2e3e3b87631b5667ecf
info  HTTP server listening on http://0.0.0.0:1337
info    - No authentication
info    - Not serving HTTPS
info  Automatic updates are disabled
info  SSH server disabled
events.js:187
      throw er; // Unhandled 'error' event
      ^
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error VS Code exited unexpectedly with code 1
```
Visual Studio Code - Current version: 2.2.0
supervisor 222
HassOS 3.13

**Comment by Frits1980** [comment] 2020-05-10 19:34
I wonder if there changed anything to the way it connects to HA, because it looks like it works perfect without autocomplete (of HA entities, etc) the second it can't connect to HA to load the autocomplete , it gives the error. So I now make sure I have:
A. only 1 tab with VSCode open in my browser at all time. If I by accident open VSCode in another I close all tabs with HA and start over.
B. Before clicking anything inside the VSCode editor after page load I wait for the breadcrumb above the code from a file to fully load ( takes about 3 sec) and show not only the file path, but also the object path.
Only then it works without giving the error.

**Comment by Vinestou** [comment] 2020-05-14 10:40
Both Chrome and Firefox give me the error. After that the add-on page goes black. 
Hardware:
Asrock J4105m running proxmox. Home Assistant in a Ubuntu Server 18.04 VM.

I get the following error in add-on log:

> [services.d] done.
> [12:36:04] INFO: Starting the code server...
> info  code-server 3.1.1 28e91ba70cd70fa9adf3f2e3e3b87631b5667ecf
> info  HTTP server listening on http://0.0.0.0:1337
> info    - No authentication
> info    - Not serving HTTPS
> info  Automatic updates are disabled
> info  SSH server disabled
> events.js:187
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
> Emitted 'error' event on Socket instance at:
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   errno: 'ECONNRESET',
>   code: 'ECONNRESET',
>   syscall: 'read'
> }
> error VS Code exited unexpectedly with code 1

**Comment by Krexatex** [comment] 2020-05-18 05:52
Having the same issue as everyone else here. 
Here is my setup:
hassio runnning on a Raspberry pi3.
Configuration is the default one.

I do not get any add-on log error, however in developer tools, I am seeing the following errors:
`workbench.web.api.js:3599 Error received from starting extension host`
`workbench.web.api.js:3599 Error: handshake timeout`
`  ERR [remote-connection][ExtensionHost][edd21…][initial][homeassistant:8123] the handshake took longer than 10 seconds. Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114`
![Screen Shot 2020-05-17 at 11 50 15 PM](https://user-images.githubusercontent.com/27723274/82178506-64fde300-9899-11ea-8c2b-9cba72ab3e48.png)

**Comment by JBurkeHansen** [comment] 2020-05-18 09:39
Same problem as above, my log shows:

(node:461) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit

Perhaps thats a hint.

System:

Hostname | homeassistant
-- | --
System | HassOS 3.13
Deployment | production

Version | 222
-- | --
Latest version | 222

newest version
0.109.6

**Comment by Frits1980** [comment] 2020-05-18 20:04
I opened an [issue ](https://github.com/keesschollaart81/vscode-home-assistant/issues/333)about this issue on the Home-Assistant extension from Kees Schoollaart. Because when I disable his extension in vscode the error never occurs. Logical, because it is somewhere in the connection with HA where the error occurs. So I hope that either Kees or Frenck (or both) can take a look at this and figure out where the problem is.

**Comment by janvankeulen** [comment] 2020-05-22 16:47
I have the same problem with Chrome but with Edge it works fine...

**Comment by GrandNewbien** [comment] 2020-05-26 21:03
Been having the same problem as well

**Comment by pinkzeppelinx** [comment] 2020-05-28 17:03
Same issue with FireFox, works on Chrome

2.2.0

**Comment by petermeijer** [comment] 2020-05-28 21:00
After rebooting my Home Assistant, I got the same issue. Could it be an issue with https? I switched back to http (using the ip of my home assistant instance) and it worked just fine.

Switching back to https seems to break it for me.

Hope this helps.

**Comment by frenck** [comment] 2020-05-30 20:48
V2.3.0 of the add-on has been released, this should address this issue. 👍

**Closed by frenck** 2020-05-30 20:48 UTC

**Comment by Frits1980** [comment] 2020-06-03 10:56
I wish it wasn't true, but I still have this issue.
Supervisor 225
VSCode 2.3.0
HA 0.110.4
Ubuntu 18.04.4 LTS

**Comment by Adorem** [comment] 2020-06-04 11:20
Yep same here the problem is still here.

. | .
-- | --
arch | x86_64
chassis | embedded
dev | false
docker | true
hassio | true
host_os | HassOS 4.8
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.43
python_version | 3.7.7
supervisor | 226
timezone | Europe/Paris
version | 0.110.4
virtualenv | false

![image](https://user-images.githubusercontent.com/38832853/83750725-fb861e80-a665-11ea-98ad-14348b33cc7e.png)

**Comment by JBurkeHansen** [comment] 2020-06-06 17:47
Yes unfortunately the bug is still there

**Comment by jpgnz** [comment] 2020-06-06 23:17
Same issue for me also. Don't think this is fixed @frenck 

Brand new install of the vmdk image
Supervisor 227
VSCode 2.3.0
HA 0.110.5

Same image as @Adorem every ~10 seconds.

**Comment by DaLassOnline** [comment] 2020-06-09 12:58
Same issue here. Tried to reinstall Visual Studio code addon, but with no effect.
When I run the addon and select the option "Open Web UI" or the ingress shortcut on the navigation bar, Visual Studio Code starts and shows connecting in the lower left corner.
When connected, it takes about 5 seconds before the message "Cannot reconnect. Please reload the window" appears. The connection in the lower left corner shows "disconnected".

Some install info:
- VMDK of HA
- Supervisor 227
- HassOS 4.10
- Home Assistant 0.110.6 (Already have this issue a while, appears on lower versions too).
- VSCode 2.3.0 (Already have this issue a while, appears on lower versions too).
- No additional configuration for Visual Studio Code.

What is needed to reopen this issue?

**Comment by kastro123** [comment] 2020-06-09 15:58
Fore me the same, it was problem before 0.110.x
VSCode 2.3.0
HASS.IO 0.110.6
Ubuntu 18.04.4 LTS

**Comment by Frits1980** [comment] 2020-06-11 12:25
"What is needed to reopen this issue?"

I think maybe tag @frenck ?

**Comment by frenck** [comment] 2020-06-11 12:46
Well, certainly not tagging, as that is generally not appreciated.

There is nothing I can do about this issue. Sorry.

**Comment by DaLassOnline** [comment] 2020-06-11 12:50
Ok, that is not the answer I expected. 

At least can you tell us how to bring the addon to a clean state by removing the pre-configured extensions to see if the problem is related to one of them?

**Comment by frenck** [comment] 2020-06-11 12:51
> At least can you tell us how to bring the addon to a clean state by removing the pre-configured extensions to see if the problem is related to one of them?

There is no such a thing as the extensions are baked in.

You can reset the setting, see add-on manual.

**Comment by DaLassOnline** [comment] 2020-06-11 12:52
Also no option to disable the extensions?

**Comment by frenck** [comment] 2020-06-11 12:56
Maybe look at the visual studio code documentation?

Please note, I have 8 instances of Home Assistant running (for dev, testing, and my production). To this date I was unable to reproduce any of this.

If anybody creates an issue that exactly points out the problem and a step by step reproducible re-production scenario, I'm happy to take a look.

Right now, I have no other option than ignoring this issue.

**Comment by Frits1980** [comment] 2020-06-11 13:17
Sorry for the tag then. What is the proper (not offending) way to get your attention again to a closed issue (for possible future issues)?

**Comment by frenck** [comment] 2020-06-11 13:18
You don't. Open a proper issue and it gets handled, or open a PR to fix stuff.
