### ISSUE TITLE
Property xxxxx is not allowed

### ISSUE THREAD

**Issue by yang3535** [hassio-addons/addon-vscode#385] opened 2022-01-26 14:12 UTC
# Problem/Motivation

The code helper is broken and displays errors when it shouldn't.  This manifests most often as "Property xxxxx is not allowed".  I assume this a known problem since it is so obnoxious, but I haven't seen it submitted anywhere.

## Expected behavior

Code helper should not report false errors

## Actual behavior

The code helper is broken and displays errors when it shouldn't.  This manifests most often as "Property xxxxx is not allowed". 

## Steps to reproduce

Very obvious in almost any body of yaml.
![property not allowed](https://user-images.githubusercontent.com/14240918/151178533-fde62c80-aef7-4ff2-b8a9-2f96e1a34cc0.jpg)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2022-01-26 14:17
Duplicate of #384 and #382

**Closed by frenck** 2022-01-26 14:17 UTC
