### ISSUE TITLE
Studio code server don't start

### ISSUE THREAD

**Issue by Simonz82** [hassio-addons/addon-vscode#693] opened 2023-08-20 13:33 UTC
Hi all,
how relsolve this:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.10.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (amd64 / qemux86-64)
 Home Assistant Core: 2023.8.3
 Home Assistant Supervisor: 2023.08.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[15:30:47] INFO: Configuring timezone (Europe/Rome)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
s6-rc: info: service legacy-services: starting
[15:30:49] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2023-08-20T13:30:50.474Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-08-20T13:30:51.599Z] info  code-server 4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c
[2023-08-20T13:30:51.602Z] info  Using user-data-dir /data/vscode
[2023-08-20T13:30:51.631Z] info  Using config file ~/.config/code-server/config.yaml
[2023-08-20T13:30:51.631Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-08-20T13:30:51.631Z] info    - Authentication is disabled
[2023-08-20T13:30:51.631Z] info    - Not serving HTTPS
[2023-08-20T13:30:51.631Z] info  Session server listening on /data/vscode/code-server-ipc.sock`

thanks
Simone

**Comment by hase-00** [comment] 2023-08-20 20:36
Same issue here. The start protocol looks like Simone's one.
I do not see some failure indication.

But ich use a Raspberry Pi4/4GByte:

Add-on version: 5.10.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.8.3
 Home Assistant Supervisor: 2023.08.1

Tanks,
Gerald

**Comment by frenck** [comment] 2023-08-20 21:05
There is nothing wrong with the logs provided. They look great.

Please provide an description on what is happening and provide a step-by-step reproduction scenario that allows me to reproduce your issue.

../Frenck

**Comment by hase-00** [comment] 2023-08-21 00:05
Okay.
I reinstall VSCode addon as normally done in HASS - done. No problem so far, now it needs to be started,
At this point there is no protocol entry - sure.
I enabled all four options und 'Information' and did not made any configuration under 'Configuration'.
Then I pressed 'Start' and checked the protocol (protocol see above). But the state indicator does not go to green and thats is why I can not start the UI, neither in the addon' dialog (sure the button is not yet available) nor via the sidebar.

I started the terminal and saw that ~/.config/code-server directory does not exist.

/Gerald

**Comment by frenck** [comment] 2023-08-21 06:47
None of what you describe is in control of an add-on, but are Home Assistant parts.

The logs you shared shows the add-on os running and started successfully.

**Comment by hase-00** [comment] 2023-08-21 09:19
@frenck tanks for the hint.
In fact it was a HASS issue as you suspected.
Solution:
- execute 'shutdown -h now' in the console,
- switch off hardware electrically,
- wait a few seconds and switch on again.

I remember having a similar problem with another addon a longer time ago with same solution.

Tanks, Gerald.

**Comment by frenck** [comment] 2023-08-21 09:22
Glad it is resolved. In that case, I'm going to close the issue on this end.
If you keep experiencing issues like these, please make sure to file an issue on the Home Assistant Supervisor project 🙏 

Thanks!

../Frenck

**Closed by frenck** 2023-08-21 09:22 UTC

**Comment by Simonz82** [comment] 2023-08-22 07:43
> @frenck tanks for the hint. In fact it was a HASS issue as you suspected. Solution:
> 
> * execute 'shutdown -h now' in the console,
> * switch off hardware electrically,
> * wait a few seconds and switch on again.
> 
> I remember having a similar problem with another addon a longer time ago with same solution.
> 
> Thanks, Gerald.

thanks, i reboot virtual machine. now work.
