### ISSUE TITLE
New 4.0 does not work when accessing HA through reverse proxy

### ISSUE THREAD

**Issue by DanDon** [hassio-addons/addon-vscode#371] opened 2022-01-13 14:57 UTC
# Problem/Motivation

New 4.0 update has stopped access to the add-on

## Expected behavior

When opening the Web-UI for the add-on, it should just display and work correctly

## Actual behavior

After a few seconds of a blank page an error box is shown with "An unexpected error occurred that requires a reload of this page." 
"The workbench failed to connect to the server (Error: Time limit reached)"

## Steps to reproduce

Visit the Visual Studio Code add-on Web-UI using a reverse proxy on an HTTPS connection

## Proposed changes

This worked correctly on previous versions but has now stopped working ... the add-on is accessible when browsing HA directly on the local network using the local IP address without HTTPS.

**Comment by bakerkj** [comment] 2022-01-13 23:06
As I noted in my ticket #372 I saw this exact same problem when upgrading from 3.7 to 4.0.

**Comment by bakerkj** [comment] 2022-01-16 20:13
@frenck is there any additional information we could provide you to help get to the bottom of this?

**Comment by sinclairpaul** [comment] 2022-01-16 20:28
I would suggest, test it under a different proxy (I'm going to assume both reports are Apache), and also look upstream for issues.  The addon wraps Code-Server, the major changes were in that release.

**Comment by bakerkj** [comment] 2022-01-16 21:13
This looks like it could be related https://github.com/coder/code-server/issues/4723.

**Comment by frenck** [comment] 2022-01-17 07:50
@bakerkj not sure why you tagged me. I don't know if I need extra information as I haven't looked into it 🤷

If I need something I would post that.

**Comment by zechnkaas** [comment] 2022-01-17 07:53
Hi, i'm using caddy and I have no issues with 4.0.0 or 4.1.0

**Comment by nmsousa76** [comment] 2022-02-04 19:47
I have teh same issue on 4.1.  I have reverted to 3.7 to continue to work.   my Hass box is running behind a Apache Reverse Proxy, and this is the only addon that is not working.

**Comment by krkeegan** [comment] 2022-02-07 19:08
Same issue running Apache.  

I _think_ the issue may be with the websocket for:
`wss://[OMITTED]/api/hassio_ingress/y4rwC26P07DpoptstoiaiyLRiYo2Nd8GIxJruCNcLV8/?type=Management&reconnectionToken=[OMITTED]&reconnection=false&skipWebSocketFrames=false`

Inspecting it in chrome, I don't see any response to the initial auth message when accessing through the proxy, while without a proxy I see a near immediate response.

**Comment by bakerkj** [comment] 2022-03-10 14:36
This is still broken and clearly impacting many users. Please don't close the issue.

**Comment by magnogabri** [comment] 2022-03-11 09:41
I can confirm the problem with Studio Code Server 4.1.0 and Home Assistant 2022.3.3.
Below is my apache configuration: 

  ProxyPreserveHost On
  ProxyRequests Off
  ProxyPass /api/websocket ws://192.168.100.184:8123/api/websocket
  ProxyPassReverse /api/websocket ws://192.168.100.184:8123/api/websocket
  ProxyPass / http://192.168.100.184:8123/
  ProxyPassReverse / http://192.168.100.184:8123/

  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)  ws://192.168.100.184:8123/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)  http://192.168.100.184:8123/$1 [P,L]

**Comment by DanDon** [comment] 2022-03-11 10:08
Also having the same issue since the 4.0 update where Studio Code cannot be accessed using an apache reverse proxy.

**Comment by demolitionfabi** [comment] 2022-03-11 11:11
Same here!

**Comment by krazos** [comment] 2022-03-11 11:28
This was the push I needed to migrate my reverse proxy server from Apache to NGINX, which had been on my long term to do list for years. I set up NGINX Proxy Manager via Docker Compose, and recreating the proxy hosts was much less painful than I had feared. If migrating is feasible for anyone, I would highly recommend it.

**Comment by jyavenard** [comment] 2022-03-16 02:12
> This was the push I needed to migrate my reverse proxy server from Apache to NGINX, which had been on my long term to do list for years. I set up NGINX Proxy Manager via Docker Compose, and recreating the proxy hosts was much less painful than I had feared. If migrating is feasible for anyone, I would highly recommend it.

moving to nginx won't help you resolving this issue.

**Comment by krazos** [comment] 2022-03-16 11:41
YMMV, I suppose, but the default configuration in NGINX Proxy Manager works flawlessly with my Home Assistant instance, including the Studio Code Server 4.1.0 add-on, without the errors that I had encountered using Apache reverse proxy.

**Comment by demolitionfabi** [comment] 2022-03-16 13:42
To circumvent the issue, I'm ussing the private IP address of my server (http://192.168.x.x:8123) to access Home Assistant + Stuio Server when I'm at home.
When I'm not at home, I normally don't want to change the configuration anyway, but if I still need to do that and connect through Apache (https://homeassistant.mydomain.com) to my Home Assistant, I use the File Editor Add-on that also works through Apache.

**Comment by pcuser42** [comment] 2022-04-23 08:53
Still happens for me on Home Assistant 2022.4.6

**Comment by krkeegan** [comment] 2022-04-23 13:59
The issue is solved if you follow the solution and upgrade Apache as noted here:

https://github.com/coder/code-server/issues/4723

**Comment by pcuser42** [comment] 2022-04-24 23:16
Confirmed that updating Apache to 2.4.53 fixed the issue for me.

**Comment by sinclairpaul** [comment] 2022-04-24 23:26
Closing, as it's not related to the addon.

**Closed by sinclairpaul** 2022-04-24 23:26 UTC
