### ISSUE TITLE
Can not run on Pi

### ISSUE THREAD

**Issue by pcopa** [hassio-addons/addon-vscode#33] opened 2019-05-04 14:36 UTC
# Problem/Motivation

> Just a suggestion.
## Expected behavior

> "Assumed" that it would run on a pi
## Actual behavior

> got an error message "This add-on is not available on your system."

## Steps to reproduce

> try to install it on a pi

## Proposed changes

> Add a remark/warning in the text that it will not run on Pi/ARM ...

**Comment by tjorim** [comment] 2019-05-04 14:44
Duplicate of https://github.com/hassio-addons/addon-vscode/issues/7 and https://github.com/hassio-addons/addon-vscode/issues/31. The VSCode add-on simply cannot run on a Raspberry Pi (armhf/armv7 architectures) yet.
Feel free to open a feature request @ hass.io to improve on the error message, this is out of control for an add-on developer.

**Closed** 2019-05-06 17:33 UTC

**Comment by jerrychong25** [comment] 2019-05-25 04:40
Hope this feature will enable in ARM architecture soon. 

As there is some minor issue on macOS for Cloud 9 IDE.

Reference: https://github.com/hassio-addons/addon-ide/issues/40
