### ISSUE TITLE
Modern-style template sensor definition results in linter errors.

### ISSUE THREAD

**Issue by nikipore** [hassio-addons/addon-vscode#418] opened 2022-03-29 20:05 UTC
# Problem/Motivation

> Modern-style template sensor definitions result in linter errors, no matter whether the `template` key is in `config/configuration.yaml` or in some yaml package.

## Expected behavior

> A valid template sensor definition should not result in a linter error.

## Actual behavior

> A valid template sensor definition results in a linter error
```json
[{
	"resource": "/config/packages/test.yaml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Incorrect type. Expected \"array\".",
	"source": "yaml-schema: http://schemas.home-assistant.io/integration-homeassistant-packages",
	"startLineNumber": 2,
	"startColumn": 3,
	"endLineNumber": 6,
	"endColumn": 1
}]
```

## Steps to reproduce

> Add this block to `config/configuration.yaml`:
```yaml
template:
  binary_sensor:
    - name: test
      state: >
        {{ true }}
```

## Proposed changes

> Fix the Home Assistant yaml schema.

**Comment by sinclairpaul** [comment] 2022-03-29 21:21
The VSCode extension repo is at https://github.com/keesschollaart81/vscode-home-assistant

Please log your issues there

**Comment by sinclairpaul** [comment] 2022-03-29 21:22
Actually I may have closed this too soon, it looks like it could be the yaml linter, either way there isn't much for the addon to fix.

**Comment by nikipore** [comment] 2022-04-01 21:31
I'll wait and see what you tell me to do.

**Comment by sinclairpaul** [comment] 2022-04-02 00:16
Nothing to do, the issue is either with the yaml linter or the HA one, will close this out as it can't be fixed here.

**Closed by sinclairpaul** 2022-04-02 00:16 UTC

**Comment by nikipore** [comment] 2022-04-02 07:52
Opened https://github.com/keesschollaart81/vscode-home-assistant/issues/2012.
