### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by 1Euro7Cent** [hassio-addons/addon-vscode#673] opened 2023-07-03 10:31 UTC
# Problem/Motivation

> it is not starting
## Expected behavior

> to start

## Actual behavior

> it started but no ui and then it is stopped

## Steps to reproduce

> start it? most likely it is only happening on my side

sample vid:

https://github.com/hassio-addons/addon-vscode/assets/67194495/872dbfc2-a0c4-495c-9bc5-111303f088e2

<details>
<summary>Log</summary>
<br>

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.3  (amd64 / qemux86-64)
 Home Assistant Core: 2023.6.3
 Home Assistant Supervisor: 2023.06.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[12:16:04] INFO: Configuring timezone (Europe/Berlin)...
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service init-mysql successfully started
s6-rc: info: service code-server successfully started
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
[12:16:05] INFO: Starting code-server...
s6-rc: info: service legacy-services successfully started
[2023-07-03T10:16:06.570Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-07-03T10:16:07.203Z] info  code-server 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a
[2023-07-03T10:16:07.204Z] info  Using user-data-dir /data/vscode
[2023-07-03T10:16:07.232Z] info  Using config file ~/.config/code-server/config.yaml
[2023-07-03T10:16:07.232Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-07-03T10:16:07.232Z] info    - Authentication is disabled
[2023-07-03T10:16:07.232Z] info    - Not serving HTTPS
[2023-07-03T10:16:07.233Z] info  Session server listening on /data/vscode/code-server-ipc.sock
```

</details>

**Comment by vednolacni** [comment] 2023-07-03 11:27
i have the same problem...

**Comment by aanban** [comment] 2023-07-03 12:09
the same thing happened here. I was editing and just changed the view. After returning the studio-code-server was stopped and could not be started again. 

- system reboot
- deinstall studio-code-server
- reinstall studio-code-server
- restart HA

did not help, the problem persists


the specific log tells following: 

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Studio Code Server
 Fully featured Visual Studio Code (VSCode) experience integrated in the Home Assistant frontend.
-----------------------------------------------------------
 Add-on version: 5.8.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 11 (bullseye)  (amd64 / qemux86-64)
 Home Assistant Core: 2023.6.3
 Home Assistant Supervisor: 2023.06.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[14:01:34] INFO: Configuring timezone (Europe/Berlin)...
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service base-addon-timezone successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-user: starting
s6-rc: info: service init-mysql: starting
s6-rc: info: service init-mosquitto: starting
s6-rc: info: service init-code-server: starting
s6-rc: info: service init-code-server successfully started
s6-rc: info: service init-mysql successfully started
s6-rc: info: service init-user successfully started
s6-rc: info: service code-server: starting
s6-rc: info: service code-server successfully started
[14:01:35] INFO: Starting code-server...
s6-rc: info: service init-mosquitto successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[2023-07-03T12:01:36.293Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-07-03T12:01:36.949Z] info  code-server 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a
[2023-07-03T12:01:36.951Z] info  Using user-data-dir /data/vscode
[2023-07-03T12:01:36.972Z] info  Using config file ~/.config/code-server/config.yaml
[2023-07-03T12:01:36.972Z] info  HTTP server listening on http://0.0.0.0:1337/
[2023-07-03T12:01:36.972Z] info    - Authentication is disabled
[2023-07-03T12:01:36.973Z] info    - Not serving HTTPS
[2023-07-03T12:01:36.973Z] info  Session server listening on /data/vscode/code-server-ipc.sock

```

**Comment by andrewmooreio** [comment] 2023-07-03 13:59
The add-on itself seems healthy, the container is running and is listening on the required port.

I think the issue is with the health reporting. Home Assistant _thinks_ the add-on isn't running, even though it is.

Stopping the add-on, disabling Watchdog and starting the add-on fixes it for me.

**Comment by varadujagan** [comment] 2023-07-03 14:01
yes for me too disabling Watchdog and starting the add-on ..... works now

**Comment by slongneck** [comment] 2023-07-03 19:02
I can confirm that disabling Watchdog and starting the the add-on allows it to start and continue running

**Comment by fwartner** [comment] 2023-07-04 07:10
Same over here.
The problem occurred when I updated ESPHome.

**Comment by chrkeijzer** [comment] 2023-07-04 08:57
I got the same problem. After disabling the Watchdog and a restart of HA, its running again.

**Comment by frenck** [comment] 2023-07-04 11:27
fixed in https://github.com/hassio-addons/addon-vscode/releases/tag/v5.8.1

**Closed by frenck** 2023-07-04 11:27 UTC

**Comment by varadujagan** [comment] 2023-07-04 14:28
I updated to v5.8.1..... now working with Watchdog enabled..... thankyou
