### ISSUE TITLE
Add support for 'not' HA conditions

### ISSUE THREAD

**Issue by mfncl99** [hassio-addons/addon-vscode#108] opened 2020-06-01 18:28 UTC
As of HA v. 0.110, `not` conditions are supported in automations: https://www.home-assistant.io/blog/2020/05/20/release-110/#support-for-not-conditions-in-automations

Currently, the editor calls out `not` as an invalid value, stating that "and" is a valid value where 'not' is used.

`  condition:
  - condition: not
    conditions:
    - condition: state`

Please add support for 'not' in condition statements for automations. Thanks!

<blockquote><img src="https://www.home-assistant.io/images/blog/2020-05-0.110/social.png" width="48" align="right"><div><img src="/images/favicon-192x192.png" height="14"> Home Assistant</div><div><strong><a href="https://www.home-assistant.io/blog/2020/05/20/release-110/">0.110: Speed! OpenZWave beta, HomeKit Cameras, ONVIF, Calendars</a></strong></div><div>0.110: Ready for one of the biggest releases in our history? Lots of UI and speed improvements, a calendar panel, OpenZWave beta, HomeKit, ONVIF sensors, ignore everything, NOT conditions, ...</div></blockquote>

**Comment by sinclairpaul** [comment] 2020-06-01 18:43
Duplicate of #106 

You would need to reference the already logged issue upstream

**Closed** 2020-06-01 18:49 UTC
