### ISSUE TITLE
CPU hogging

### ISSUE THREAD

**Issue by apedance** [hassio-addons/addon-vscode#114] opened 2020-06-20 14:55 UTC
The addon is taking up a whole CPU core and leaving it on 99%.

**Comment by OptimusGREEN** [comment] 2020-08-04 05:50
I'm also having this issue. A 3.5ghz i5 at over 90% CPU usage when this add-on the opened. It doesn't reduce when closed either until the add-on is stopped.

**Comment by jumping2000** [comment] 2020-08-25 12:29
I also hava an abnormal use of CPU with latest version (2.4.0) of the addon (or maybe latest version 0.114.x of HA supervised).

**Comment by JANogueira** [comment] 2020-10-01 08:15
Hi all,

Also having the same issue. VSCode 2.7.1, on hassio 0.115.6, installed on a RPi4 4GB (64 bit hassio version). CPU hogging is solved after restarting VSCode add-on. Nothing is shown on the add-on logs nor on supervisor logs

Only knew that VSCode was the culprit after checking on the host machine while using top and sorting per CPU usage.

**Comment by vajonam** [comment] 2020-11-09 13:40
I think this happens, when HA is restarted on a different window while the VS addon is running in another window.

**Comment by nov30th** [comment] 2021-01-05 12:54
I have the same issue, as I'm not familiar with docker, not sure how to debug/attach logs of this vscode ext.
@vajonam might be the reason as I've updated some settings got few restarts of HA core, and there are two processes runs CPU 100% of node process, (keesschollaart.vscode-home-assistant with processid or something).

**Comment by nov30th** [comment] 2021-01-17 10:54
from the 100% CPU process, I guess it is something like looping in rendering.
I haven't notice that it is 100% always once I open the VS webpage.

![image](https://user-images.githubusercontent.com/11451122/104837658-f8882780-58f0-11eb-97ee-f474acb8ca04.png)
![image](https://user-images.githubusercontent.com/11451122/104837840-3c2f6100-58f2-11eb-91f4-885c64439cd7.png)

Today, I used VS to modify the config file, did look into the 100% CPU problem, found there is a **loop soft link** in the config folder, it might already exist for many years.
I guess the VS add-on trying to get all the files under config folder **one time** and non-stop loading, **after get the soft link removed, CPU back to normal**, no more high CPU usage.

### My case:

**The issue happens when:**
soft link looping in the config folder

**Reproduce:**
1. create loop soft link in config path by
➜  /config git:(main) ✗ ln -s /config /config/
2. open webpage of VS add-on
3. VS add-on is 100% CPU by _ps aux |grep node_

**Solved by:**
removed the looping soft link

**Comment by vajonam** [comment] 2021-01-18 16:39
I too have this config -> /config link. I have removed it, will report back on this and cpu

**Comment by frenck** [comment] 2021-01-20 14:07
For all cases I've reviewed up until now, a circular symlink was cause of the issue.

I'm closing this issue. While VSCode uses quite a bit of CPU; the symlink issue is not something the add-on can provide a solution for.

**Closed by frenck** 2021-01-20 14:07 UTC
