### ISSUE TITLE
Custom YAML full of errors after last update

### ISSUE THREAD

**Issue by OldCurmudgeon3DP** [hassio-addons/addon-vscode#395] opened 2022-03-05 15:14 UTC
# Problem/Motivation

> VSC 4.1.0 is flagging most of my custom YAML with errors even though HA checks them as valid.

## Expected behavior

> No errors, unless there was a breaking change in format that I missed.

## Actual behavior

> Errors everywhere as shown in the screenshot.

## Steps to reproduce

> I just opened the addon after not needing to edit for several months.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

<img width="644" alt="Screenshot 2022-03-05 101125" src="https://user-images.githubusercontent.com/44645861/156889233-1674126e-eb72-4d99-bfa2-d99b78cb4a85.png">

**Comment by frenck** [comment] 2022-03-05 15:22
Duplicate of many (closed) other issues and not an addon issue

**Closed by frenck** 2022-03-05 15:22 UTC

**Comment by OldCurmudgeon3DP** [comment] 2022-03-05 16:13
Fair enough. I didn't think to check closed issues. 🤦🏼
