### ISSUE TITLE
Studio Code Server - Erroneous error messages

### ISSUE THREAD

**Issue by MilesAheadToo** [hassio-addons/addon-vscode#393] opened 2022-02-27 08:52 UTC
# Problem/Motivation

> After updating to v4.1.0 I am getting incorrect error messages when viewing YAML files that work correctly, conform to formatting conventions, and did not not display errors before.

## Expected behavior

> That no errors would be shown

## Actual behavior

> SCS reports multiple errors 

## Steps to reproduce

> Create a `sensors.yaml` file that is referenced in `configuration.yaml` as below
`sensor: !include sensors.yaml`

The following code in the sensors.yaml file will generate errors on SCS
```
- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: processor_temperature

- platform: rest
  name: pws_forecast
  json_attributes:
    - calendarDayTemperatureMax
    - calendarDayTemperatureMin
    - dayOfWeek
    - expirationTimeUtc
    - moonPhase
    - moonPhaseCode
    - moonPhaseDay
    - moonriseTimeLocal
    - moonriseTimeUtc
    - moonsetTimeLocal
    - moonsetTimeUtc
    - narrative
    - qpf
    - qpfSnow
    - sunriseTimeLocal
    - sunriseTimeUtc
    - sunsetTimeLocal
    - sunsetTimeUtc
    - temperatureMax
    - temperatureMin
    - validTimeLocal
    - validTimeUtc
    - daypart
  value_template: '{{ value_json["validTimeLocal"][0] }}'
  resource: !secret wu_forecast_url
  scan_interval: 03:00:00
```

The `- platform: xxxxx` lines generate a `Property platform is not allowed.` error.
The `resources: xxxxx` lines generate a `Property resources not allowed.` error.
The `json_attributes: xxxxx` lines generate a `Property json_attributes not allowed.` error.
The `name: xxxxx` lines generate a `Property name not allowed.` error.
etc.

## Proposed changes

> SCS should not display errors for valid code.

**Comment by frenck** [comment] 2022-02-27 15:21
Duplicate of many others, please check if you issue was already reported before creating a new issue. This is not an add-on issue, but an issue in the VSCode extension.

**Closed by frenck** 2022-02-27 15:21 UTC

**Comment by MilesAheadToo** [comment] 2022-02-27 15:49
ApologiesBest RegardsTrevor Miles | +351 9 1010 8221 | Calcada Branca 108, 2755-156 Alcabideche, PortugalAzirella Ltd | 27, 25 Martiou St., D. Michael Tower, # 105, Engomi, 2408, Nicosia, CyprusFrom: Franck Nijhof ***@***.***>Sent: Sunday, 27 February 2022, 15:21To: hassio-addons/addon-vscodeCc: MilesAheadToo; AuthorSubject: Re: [hassio-addons/addon-vscode] Studio Code Server - Erroneous error messages (Issue #393)
Duplicate of many others, please check if you issue was already reported before creating a new issue. This is not an add-on issue, but an issue in the VSCode extension.

**Comment by frenck** [comment] 2022-02-27 17:19
> Apologies

Don't worry about it! 👍

**Comment by Protoncek** [comment] 2022-03-06 08:14
Frenck, do you have any information about this error? In HA there’s still no update, so i’m stuck with version 4.0.0. Just yesterday i updated to 4.1.0 again to test, but errors still show, so i went back to 4.0.0 again…
