### ISSUE TITLE
Update code-server

### ISSUE THREAD

**Issue by MitchTalmadge** [hassio-addons/addon-vscode#856] opened 2024-09-12 09:05 UTC
# Problem/Motivation

The version of the code server is quite old. Many extensions cannot be installed because of this.

```
code-server: v4.20.0
Code: 1.85.1
Commit: 0b84523121d6302fbe30eda7899ec3b81810748e
Date: 2023-12-18T20:21:20.879Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
```

Latest version at time of writing is 4.92.2: https://github.com/coder/code-server/releases

## Expected behavior

The add-on would periodically be updated with the latest code server.

## Actual behavior

The add-on is shipped with a code server from December of 2023.

## Steps to reproduce

1. Install the Addon
2. Open the editor
3. Go to the Help menu
4. Click 'About'
5. Observe old version

## Proposed changes

Let's update it! :)

**Comment by frenck** [comment] 2024-09-12 09:29
Thanks, but closing this as it is not a bug report.

../Frenck

**Closed by frenck** 2024-09-12 09:29 UTC
